spring.application.name=lab1_c4j816
spring.datasource.url=jdbc:sqlserver://163.178.173.130;databaseName=ZenithSky_C4J816_1_2026;encrypt=true;trustServerCertificate=true;

#CONFIGURACION DE LA CONEXION A LA BASE DE DATOS
spring.datasource.username=Lenguajes
spring.datasource.password=lenguajesparaiso2025
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

#context path
server.servlet.context-path=/lab1C4j816
server.port=8084
